services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://host.docker.internal:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"